services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            MONGO_INITDB_DATABASE: grafanatest
        ports:
            - 27017:27017
        volumes:
            - 05_grafana_data_container:/data/db
            - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        networks:
            - service_bridge    
        profiles: [backend]            

    elasticsearch:
        image: elasticsearch:7.16.1
        environment:
            "discovery.type": single-node
        ports:
            - "9200:9200"   
            - "9300:9300"   
        networks:
            - service_bridge       

    kibana:
        image: kibana:7.16.1
        ports:
            - "5601:5601"
        networks:
            - service_bridge   

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"    
        volumes:
            - ./provisioning:/etc/grafana/provisioning            
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - service_bridge                

volumes:
    05_grafana_data_container:

networks:
    service_bridge:
        driver: bridge        
        